payroll/employee/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('employee-show', views.employee_show, name='employee-show'),
    path('search-employees', views.search_employees, name='search-employees'),
    # path('search-by-date', views.search_by_date, name='search-by-date'),
    path('employee-add', views.employee_add, name='employee-add'),
    path('employee-update/<int:pk>', views.employee_update, name='employee-update'),
    path('employee-preferences/<int:pk>',
         views.employee_preferences, name='employee-preferences'),
    path('employee-records/<int:pk>',
         views.employee_records, name='employee-records'),
    path('emp-record-delete/<int:pk>/<int:emp_id>',
         views.emp_record_delete, name='emp-record-delete'),
    path('employee-hiring-details/<int:pk>',
         views.employee_hiring_details, name='employee-hiring-details'),
    path('employee-resume/<int:pk>', views.employee_resume, name='employee-resume'),
    path('employee-sss-contrib/<int:pk>',
         views.employee_sss_contrib, name='employee-sss-contrib'),
    path('employee-pagibig-contrib/<int:pk>',
         views.employee_pagibig_contrib, name='employee-pagibig-contrib'),
    path('employee-philhealth-contrib/<int:pk>',
         views.employee_philhealth_contrib, name='employee-philhealth-contrib'),
    path('employee-company-loan/<int:pk>',
         views.employee_company_loan, name='employee-company-loan'),
    path('employee-pagibig-loan/<int:pk>',
         views.employee_pagibig_loan, name='employee-pagibig-loan'),
    path('employee-sss-loan/<int:pk>',
         views.employee_sss_loan, name='employee-sss-loan'),
    path('employee-comloan-contrib/<int:pk>/<int:comloan>',
         views.employee_comloan_contrib, name='employee-comloan-contrib'),
    path('employee-pagibigloan-contrib/<int:pk>/<int:comloan>',
         views.employee_pagibigloan_contrib, name='employee-pagibigloan-contrib'),
    path('employee-sssloan-contrib/<int:pk>/<int:sssloan>',
         views.employee_sssloan_contrib, name='employee-sssloan-contrib'),
    path('employee-uniform/<int:pk>',
         views.employee_uniform, name='employee-uniform'),
    path('employee-medical/<int:pk>',
         views.employee_medical, name='employee-medical'),
    path('employee-canteen/<int:pk>',
         views.employee_canteen, name='employee-canteen'),
    path('employee-gatepass/<int:pk>',
         views.employee_gatepass, name='employee-gatepass'),
    path('employee-vale/<int:pk>', views.employee_vale, name='employee-vale'),
    path('employee-biodata/<int:pk>',
         views.employee_biodata, name='employee-biodata'),
    path('employee-acceptance/<int:pk>',
         views.employee_acceptance, name='employee-acceptance'),
    path('employee-acceptance-download/<int:pk>',
         views.employee_acceptance_download, name='employee-acceptance-download'),
    path('employee-return-to-work/<int:pk>',
         views.employee_return_to_work, name='employee-return-to-work'),
    path('employee-return-download/<int:pk>',
         views.employee_return_download, name='employee-return-download'),
    path('employee-clearance-form/<int:pk>',
         views.employee_clearance_form, name='employee-clearance-form'),
    path('employee-leave-absence/<int:pk>',
         views.employee_leave_absence, name='employee-leave-absence'),
    path('update-record/<int:record>',
         views.update_record, name='update-record'),
    path('employee-leave-download/<int:emp_pk>/<int:leave_pk>',
         views.employee_leave_download, name='employee-leave-download'),
    path('employee-endorsement-letter/<int:pk>',
         views.employee_endorsement_letter, name='employee-endorsement-letter'),
    path('employee-upload-picture/<int:pk>',
         views.employee_upload_picture, name='employee-upload-picture'),
    path('employee-requirements/<int:pk>',
         views.employee_requirements, name='employee-requirements'),
    path('employee-memo/<int:pk>',
         views.employee_memo, name='employee-memo'),
    path('memo-delete/<int:pk>',
         views.memo_delete, name='memo-delete'),
    path('employee-data-movement/<int:pk>',
         views.employee_data_movement, name='employee-data-movement'),
    

]

payroll/hrms/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
    path('company-show', views.company_show, name='company-show'),
    path('search-company', views.search_company, name='search-company'),
    path('company-update/<int:pk>', views.company_update, name='company-update'),
    path('print-employees/<int:pk>', views.print_employees, name='print-employees'),
    path('company-rates/<int:pk>', views.company_rates, name='company-rates'),
    path('company-gov-deducts/<int:pk>',
         views.company_gov_deducts, name='company-gov-deducts'),
    path('company-other-options/<int:pk>',
         views.company_other_options, name='company-other-options'),
    path('company-add', views.company_add, name='company-add'),
    path('company-delete/<int:pk>', views.company_delete, name='company-delete')
]

payroll/payroll/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('',include('hrms.urls')),
    path('login/', include('login.urls')),
    path('logs/', include('logs.urls')),
    path('vouchers/',include('voucher.urls')),
	path('employees/',include('employee.urls')),
	path('payroll/',include('payrolllist.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payroll/employee/models.py
from django.db import models
from hrms.models import Company
# from payrolllist.models import Payroll
from django.db.models.signals import post_save
# Create your models here.


class Employee(models.Model):
    company = models.ForeignKey(
        Company, on_delete=models.CASCADE, related_name='company')
    emp_id = models.IntegerField(default=0)
    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    address = models.CharField(max_length=255)
    provincial_address = models.CharField(max_length=255)
    date_of_birth = models.DateField()
    gender = models.CharField(max_length=50)
    place_of_birth = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    date_hired = models.DateField(null=True)
    contract_expiration = models.DateField(null=True)

    # sss_bracket = models.CharField(max_length=50)
    gov_deductions_to_implement = models.CharField(max_length=255, default="")
    sss_option = models.CharField(max_length=255, default="")
    sss_bracket = models.DecimalField(max_digits=7, decimal_places=2, default="0")
    sss_value = models.DecimalField(max_digits=7, decimal_places=2, default="0")
    pagibig_value = models.DecimalField(max_digits=7, decimal_places=2, default="0")
    philhealth_value = models.DecimalField(max_digits=7, decimal_places=2, default="0")

    sss_no = models.CharField(max_length=255, default="")
    pagibig_no = models.CharField(max_length=255, default="")
    philhealth_no = models.CharField(max_length=255, default="")
    tin_no = models.CharField(max_length=255, default="")
    civil_status = models.CharField(max_length=255)
    citizenship = models.CharField(max_length=255)
    remarks = models.CharField(max_length=255, default="")

    def __str__(self):
        return f'{self.first_name} {self.middle_name} {self.last_name}'

    def get_hiring_details(self):
        return Employee_hiring_details.objects.filter(employee=self).first()

# signal employee_preferences


def create_employee_preferences(sender, **kwargs):
    if kwargs['created']:
        employee_preferences = Employee_preferences.objects.create(
            employee=kwargs['instance'])

# signal employee_preferences


def create_employee_preferences(sender, **kwargs):
    if kwargs['created']:
        employee_preferences = Employee_preferences.objects.create(
            employee=kwargs['instance'])

# signal Employee_hiring_details


def create_hiring_details(sender, **kwargs):
    if kwargs['created']:
        employee_hiring_details = Employee_hiring_details.objects.create(
            employee=kwargs['instance'])

# signal Employee_resume


def create_resume(sender, **kwargs):
    if kwargs['created']:
        employee_resume = Employee_resume.objects.create(
            employee=kwargs['instance'])


def create_picture(sender, **kwargs):
    if kwargs['created']:
        employee_picture = Employee_picture.objects.create(
            employee=kwargs['instance'])

def create_requirements(sender, **kwargs):
    if kwargs['created']:
        employee_requirements = Employee_requirements.objects.create(employee=kwargs['instance'])

def create_acceptance(sender, **kwargs):
    if kwargs['created']:
        employee_acceptance = Employee_acceptance.objects.create(employee=kwargs['instance'])


post_save.connect(create_requirements, sender=Employee)


post_save.connect(create_employee_preferences, sender=Employee)
post_save.connect(create_hiring_details, sender=Employee)
post_save.connect(create_resume, sender=Employee)
post_save.connect(create_picture, sender=Employee)
post_save.connect(create_acceptance, sender=Employee)


class Employee_preferences(models.Model):
    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name='employee_pref')
    spouse = models.CharField(max_length=255, blank=True, null=True)
    occupation = models.CharField(max_length=255, blank=True, null=True)
    spouse_address = models.CharField(max_length=255, blank=True, null=True)
    character_reference_name = models.CharField(max_length=255)
    character_reference_address = models.CharField(max_length=255)
    character_reference_phone = models.CharField(max_length=255)

    def __str__(self):
        return f'{ self.employee } - Preferences'


class Employment_record(models.Model):
    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name='employee_rec')
    from_date = models.DateField()
    to_date = models.DateField()
    company = models.CharField(max_length=255, default="")
    position = models.CharField(max_length=255)

    def __str__(self):
        return f'{ self.employee } - Record'


class Employee_hiring_details(models.Model):
    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name='employee_hr')
    rate = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    training_rate = models.DecimalField(
        max_digits=7, decimal_places=2, null=True)
    atm = models.CharField(max_length=255)
    position = models.CharField(max_length=255)
    payment_method = models.CharField(max_length=255)

    def __str__(self):
        return f'{ self.employee } - Hiring Details'


class Employee_resume(models.Model):
    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name='employee_resume')
    resume = models.FileField(blank=True, upload_to='resume')

    def __str__(self):
        return f'{self.employee} - resume'


class Employee_picture(models.Model):
    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name='employee_picture')
    picture =   models.ImageField(upload_to='media/')

    def __str__(self):
        return f'{self.employee} - picture'



class Employee_company_loan(models.Model):
    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name='employee_com_loan')
    load_amount = models.DecimalField(
        max_digits=7, decimal_places=2, null=True)
    rate_to_deduct = models.DecimalField(
        max_digits=7, decimal_places=2, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f'{ self.employee } - Company Loan'


class Employee_pagibig_loan(models.Model):
    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name='employee_pag_loan')
    load_amount = models.DecimalField(
        max_digits=7, decimal_places=2, null=True)
    rate_to_deduct = models.DecimalField(
        max_digits=7, decimal_places=2, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f'{ self.employee } - Pagibig Loan'


class Employee_vale(models.Model):
    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name='employee_vale')
    amount = models.DecimalField(max_digits=7, decimal_places=2)
    rate_to_deduct = models.DecimalField(max_digits=7, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f'{ self.employee } - Vale'


class Employee_sss_loan(models.Model):
    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name='employee_sss_loan')
    load_amount = models.DecimalField(
        max_digits=7, decimal_places=2, null=True)
    rate_to_deduct = models.DecimalField(
        max_digits=7, decimal_places=2, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f'{ self.employee } - SSS Loan'


class Employee_sss(models.Model):
    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name='employee_sss')
    cut_off_date = models.DateField()
    contribution_collected = models.DecimalField(
        max_digits=7, decimal_places=2)

    def __str__(self):
        return f'{ self.employee } - sss'


class Employee_pagibig(models.Model):
    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name='employee_pagibig')
    cut_off_date = models.DateField()
    contribution_collected = models.DecimalField(
        max_digits=7, decimal_places=2)

    def __str__(self):
        return f'{ self.employee } - pagibig'


class Employee_philhealth(models.Model):
    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name='employee_philhealth')
    cut_off_date = models.DateField()
    contribution_collected = models.DecimalField(
        max_digits=7, decimal_places=2)

    def __str__(self):
        return f'{ self.employee } - philhealth'


class Employee_comloan_contrib(models.Model):
    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name='employee_comload_contrib')
    payroll = models.IntegerField(default=0)
    company_loan = models.ForeignKey(
        Employee_company_loan, on_delete=models.CASCADE, related_name='employee_company')
    cut_off_date = models.DateField()
    contribution_collected = models.DecimalField(
        max_digits=7, decimal_places=2)

    def __str__(self):
        return f'{ self.employee } {self.id} - company loan contrib'


class Employee_pagibigloan_contrib(models.Model):
    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name='employee_pagibigload_contrib')
    payroll = models.IntegerField(default=0)
    pagibig_loan = models.ForeignKey(
        Employee_pagibig_loan, on_delete=models.CASCADE, related_name='employee_pagibigloan_company')
    cut_off_date = models.DateField()
    contribution_collected = models.DecimalField(
        max_digits=7, decimal_places=2)

    def __str__(self):

payroll/employee/templates/employee/acceptance.html
{% extends "hrms/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">
            {{ head }}
            </h4>
        </div>
            <div class="card-body">

                        <a href='{% url "employee-acceptance-download" employee_id %}' class="btn btn-info">Download</a>
                {% include "employee/update_menu.html" %}
            </div>

    </div>

        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col example-grid-col">
                    </div>
                    <div class="col-7 example-grid-col">
                        <form method="POST" novalidate="">
                            <div class="form-group">
                                {% csrf_token %}
                                {{ form|crispy  }}
                                <input type="hidden" value="{{employee_id}}" name="employee_id">
                            </div>
                            <button type="submit" class="btn btn-success"> Save</button>
                        </form>

                    </div>
                    <div class="col example-grid-col">
                    </div>

                </div>
            </div>

        </div>

{% endblock content %}

payroll/employee/templates/employee/all_employees.html
{% extends "hrms/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="card">
		<div class="card-header">
			<h4 class="card-title">
			{{ head }}
			</h4>
		</div>
		<div class="card-body">

        <a href='{% url "employee-add" %}' class="btn btn-primary" >Add Employee</a>

        


				{% comment %} <form class="form-control" action="{% url 'search-employees' %}" method="post" style="margin-top: 10px">
						{% csrf_token %}
					<div class="row">
	            <div class="col example-grid-col">
								  <select class="form-control" name="company">
								  	<option value="">Choose company</option>
										{% for com in companies %}
											<option value="{{com.company_name}}">{{com.company_name}}</option>
										{% endfor %}
								  </select>
	            </div>
	            <div class="col example-grid-col">
	                <input type="text" class="form-control" name="employee_name" value="" placeholder="Search by employee">
	            </div>
	            
				<div class="col example-grid-col">
					<select class="form-control" name="payment_method">
						<option value="">Choose payment method</option>
							<option value="daily">daily</option>
							<option value="weekly">weekly</option>
							<option value="semi-monthly">semi-monthly</option>
							<option value="monthly">monthly</option>
					</select>
	            </div>

	            <div class="col example-grid-col">
	                <input type="text" name="start_date" value="" class="datepicker dateinput form-control"  id="id_date_hired" placeholder="Start Date">
	            </div>
	            <div class="col example-grid-col">
	                <input type="text" name="end_date" value="" class="datepicker dateinput form-control"  id="id_date_hired" placeholder="End Date">
	            </div>

	            <div class="col example-grid-col">
					<select class="form-control" name="search_by">
						<option value="">Choose Search By</option>
							<option value="date_hired">Date Hired</option>
							<option value="contract_expiration">Contract Expiration</option>
					</select>
	            </div>

	            <div class="col example-grid-col">
					<select class="form-control" name="order">
						<option value="">Choose Order</option>
							<option value="ascending">ascending</option>
							<option value="descending">descending</option>
					</select>
	            </div>

							<div class="col example-grid-col">
	                <button type="submit" class="btn btn-info" name="button">Search</button>
	            </div>
	        </div>
				</form> {% endcomment %}
				<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
			<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">

			<div class="table-responsive" style="margin-top: 10px">
				<table id="example" class="table table-striped table-bordered" style="width:100%">

					<thead class="thead-dark">
						<tr>
							<th scope="col" class="text-center">#</th>
							<th scope="col" class="text-center">Emp Id</th>
							<th scope="col" class="text-center">Employee Name</th>
							<th scope="col" class="text-center">SSS</th>
							<th scope="col" class="text-center">Phone</th>
							<th scope="col" class="text-center">Position</th>
							<th scope="col" class="text-center">Company</th>
							<th scope="col" class="text-center">Date Hired</th>
							<th scope="col" class="text-center">Contact Expiration</th>
							<th scope="col" class="text-center">Remarks</th>
							<th scope="col" class="text-center">Action</th>
						</tr>
					</thead>
					<tbody>
						{% for emp in employees %}
							<tr>
								<th class="align-middle text-center" scope="row">{{ forloop.counter}}</th>
								<td class="align-middle text-center">{{ emp.emp_id }} </td>
								<td class="align-middle text-center">{{ emp }} </td>
								<td class="align-middle text-center">{{ emp.get_hiring_details.sss }}</td>
								<td class="align-middle text-center">{{ emp.phone }}</td>
								<td class="align-middle text-center">{{ emp.get_hiring_details.position }}</td>
								<td class="align-middle text-center">{{ emp.company }}</td>
								<td class="align-middle text-center">{{ emp.date_hired }}</td>
								<td class="align-middle text-center">{{ emp.contract_expiration }}</td>
								<td class="align-middle text-center">{{ emp.remarks }}</td>
								<td class="align-middle text-center">
									<a href="{% url 'employee-update' emp.id %}" class="btn btn-info">Update</a>
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
{% endblock content %}

payroll/employee/templates/employee/employee_contrib.html
{% extends "hrms/base.html" %}
{% block content %}
	<div class="card">
		<div class="card-header">
			<h4 class="card-title">
			{{ head }}
			</h4>
		</div>
		<div class="card-body">
        {% include "employee/update_menu.html" %}
			<div class="table-responsive" style="margin-top: 10px">
				<table class="table">
					<thead class="thead-dark">
						<tr>
							<th scope="col" class="text-center">#</th>
							<th scope="col" class="text-center">Cut Off Date</th>
							<th scope="col" class="text-center">Contribution</th>
						</tr>
					</thead>
					<tbody>
						{% for cont in contribution %}
							<tr>
								<th class="align-middle text-center" scope="row">{{ forloop.counter}}</th>
								<td class="align-middle text-center">{{ cont.cut_off_date }} </td>
								<td class="align-middle text-center">{{ cont.contribution_collected }}</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
{% endblock content %}

payroll/employee/templates/employee/employee_data_movement.html
{% extends "hrms/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="card">
		<div class="card-header">
			<h4 class="card-title">
			{{ head }}
			</h4>
		</div>
		<div class="card-body">
            {% include "employee/update_menu.html" %}
           

			<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
			<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">

<!--			<div class="table-responsive" style="margin-top: 10px">-->
<table id="example" class="table table-striped table-bordered" style="width:100%">
					<thead class="thead-dark">
						<tr>
							<th scope="col" class="text-center">#</th>
							<th scope="col" class="text-center">Action</th>
							<th scope="col" class="text-center">Action By</th>
							<th scope="col" class="text-center">Date</th>

						</tr>
					</thead>
					<tbody>
						{% for log in logs %}
							<tr>
								<th class="align-middle text-center">{{ forloop.counter}}</th>
								<td class="align-middle text-center">{{ log.action }} </td>
								<td class="align-middle text-center">{{ log.action_by }} </td>
								<td class="align-middle text-center">{{ log.action_date}}</td>

							</tr>
						{% endfor %}
					</tbody>
				</table>
<!--			</div>-->


		</div>
	</div>

{% endblock content %}

payroll/employee/templates/employee/employee_gov_contrib.html
{% extends "hrms/base.html" %}
{% block content %}
	<div class="card">
		<div class="card-header">
			<h4 class="card-title">
			{{ head }}
			</h4>
		</div>
		<div class="card-body">
        {% include "employee/update_menu.html" %}
			<div class="table-responsive" style="margin-top: 10px">
				<table class="table">
					<thead class="thead-dark">
						<tr>
							<th scope="col" class="text-center">#</th>
							<th scope="col" class="text-center">Cut Off Date</th>
							<th scope="col" class="text-center">Contribution</th>
						</tr>
					</thead>
					<tbody>
						{% for cont in contribution %}
							<tr>
								<th class="align-middle text-center" scope="row">{{ forloop.counter}}</th>
								<td class="align-middle text-center">{{ cont.base_payroll }} </td>
								<td class="align-middle text-center">
								{% if kind == "pagibig" %}
								    {{ cont.pagibig }}	
								{% elif kind == "philhealth" %}
									 {{ cont.philhealth }}					    
																	
								{% elif kind == "sss" %}
									 {{ cont.sss }}				    
																		
								{% endif %}
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
{% endblock content %}

payroll/employee/templates/employee/employee_leave_absence.html
{% extends "hrms/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="card">
		<div class="card-body">
			{% include "employee/update_menu.html" %}
		</div>
</div>

	<div class="card">
		<div class="card-body">
			<div class="row">
				<div class="col example-grid-col">
				</div>
				<div class="col-7 example-grid-col">
					<form method="POST" novalidate="">
						<div class="form-group">
							{% csrf_token %}
							{{ form|crispy  }}
						</div>
						<input type="hidden" name="employee_id" value="{{employee.pk}}">
						<button type="submit" class="btn btn-success"> Save</button>
					</form>
				</div>
				<div class="col example-grid-col">
				</div>
			</div>

		</div>

	</div>

  {% if may_leave %}

  <div class="card">
		<div class="card-body">
			<div class="table-responsive" style="margin-top: 10px">
				<table class="table">
					<thead class="thead-dark">
						<tr>
							<th scope="col" class="text-center">#</th>
							<th scope="col" class="text-center">Start Date </th>
							<th scope="col" class="text-center">End Date</th>
							<th scope="col" class="text-center">No of Days</th>
							<th scope="col" class="text-center">Action</th>
						</tr>
					</thead>
					<tbody>
						{% for leave in may_leave %}
							<tr>
								<th class="align-middle text-center" scope="row">{{ forloop.counter}}</th>
								<td class="align-middle text-center">{{ leave.start_date }} </td>
								<td class="align-middle text-center">{{ leave.end_date }}</td>
								<td class="align-middle text-center">{{ leave.no_of_days }}</td>
								<td class="align-middle text-center">
                  				<a href="{% url 'employee-leave-download' employee.pk leave.pk %}" class="btn btn-warning btn-sm">Download</a>
                  
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
</div>
		</div>
	</div>

  {% endif %}



{% endblock content %}

payroll/employee/templates/employee/employee_memo.html
{% extends "hrms/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

	<div class="card">
		<div class="card-body">
		  {% include "employee/update_menu.html" %}
		  
			<div class="row">
				<div class="col example-grid-col">
				</div>
				<div class="col-7 example-grid-col">
					<form method="POST" novalidate="" enctype=multipart/form-data>
						<div class="form-group">
							{% csrf_token %}
							{{ form|crispy  }}
						</div>
						<button type="submit" class="btn btn-success"> Save</button>
						
					</form>
				</div>
				<div class="col example-grid-col">
				</div>
			</div>

		</div>

	</div>


{% if may_memo %}

  <div class="card">
		<div class="card-body">
			<div class="table-responsive" style="margin-top: 10px">
				<table class="table">
					<thead class="thead-dark">
						<tr>
							<th scope="col" class="text-center">#</th>
							<th scope="col" class="text-center">memo</th>
							<th scope="col" class="text-center">Action</th>
						</tr>
					</thead>
					<tbody>
						{% for memo in may_memo %}
							<tr>
								<th class="align-middle text-center" scope="row">{{ forloop.counter}}</th>
								<th class="align-middle text-center" scope="row">{{ memo.memo }}</th>
								<td class="align-middle text-center">

					<a href="/media/{{memo.memo}}" class="btn btn-info">Download Memo</a>
                 							
													
				  <form style="display:inline" action="{% url 'memo-delete' memo.pk %}" method="post">
                    {% csrf_token %}
                    <button type="submit" onclick="return confirm('Are you sure you want to delete this memo?');" name="button" class="btn btn-danger">Delete</button>
                  </form>

								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
</div>
		</div>
	</div>

  {% endif %}


{% endblock content %}

payroll/employee/templates/employee/employee_resume.html
{% extends "hrms/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

	<div class="card">
		<div class="card-body">
		  {% include "employee/update_menu.html" %}
		  
			<div class="row">
				<div class="col example-grid-col">
				</div>
				<div class="col-7 example-grid-col">
					<form method="POST" novalidate="" enctype=multipart/form-data>
						<div class="form-group">
							{% csrf_token %}
							{{ form|crispy  }}
						</div>
						<button type="submit" class="btn btn-success"> Save</button>
						<div align="right">
							<a href="{% url 'employee-biodata' pk %} "class="pull-right btn btn-info">Download Biodata / Resume </a>
						</div>

					</form>
				</div>
				<div class="col example-grid-col">
				</div>
			</div>

		</div>

	</div>


{% endblock content %}